#Nombre de la aplicacion
spring.application.name="Pet Care"

# application.properties
# Configuracion de la base de datos
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# Configuracion de JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#JWT
jwt.secret.key=${SPRING_JWT_ACCESS_KEY}
jwt.time.expiration.access.key=${SPRING_JWT_TIME_EXPIRATION_ACCESS_KEY}
jwt.time.expiration.refresh.key=${SPRING_JWT_TIME_EXPIRATION_REFRESH_KEY}

# Configuracion del nivel de registro para Spring
# Muestra mensajes informativos del framework Spring
logging.level.org.springframework=info
# Muestra solo errores graves de Hibernate
logging.level.org.hibernate=error
# Muestra advertencias y errores a nivel general para toda la aplicacion.
logging.level.root=INFO
# Configuracion de formato de fecha y hora para los logs
# Formato de salida en la consola  %d{yyyy-MM-dd HH:mm:ss} - %highlight(%p) - %msg%n
logging.pattern.console=%d{HH:mm:ss} - %highlight(%p) - %msg%n
# Formato de salida en archivo  %d{yyyy-MM-dd HH:mm:ss} - %highlight(%p) - %msg%n
logging.pattern.file=%d{HH:mm:ss} - %highlight(%p) - %msg%n

